<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexaCommerce.Common\NexaCommerce.Common.csproj" />
    <ProjectReference Include="..\NexaCommerce.Data\NexaCommerce.Data.csproj" />
    <ProjectReference Include="..\NexaCommerce.Domain\NexaCommerce.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
